### ISSUE TITLE
Bug in __init__

### ISSUE THREAD

**Issue by mathewtrivett** [ericmjl/nxviz#153]
* nxviz version: 0.3.2
* Python version: 3.5
* Operating System: OSX

### Description

I was trying to import nxviz into a Jupyter notebook and hit this error.

### What I Did

```
import nxviz as nv

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-0cc1ed72028f>", line 2, in <module>
    import nxviz as nv

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nxviz/__init__.py", line 1, in <module>
    from nxviz.plots import ArcPlot, CircosPlot, MatrixPlot  # NOQA

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nxviz/plots.py", line 87
    logging.debug(f'INIT: {self.sm}')
                                   ^
SyntaxError: invalid syntax
```

**Comment by ericmjl** [comment]
This is related to the use of [f-strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) in Python 3.6. They're a very convenient tool for developers, but are only available to Py36. If possible, do upgrade to 3.6 - it's a minor thing to do if you're already developing on 3.5, and if I remember correctly, there should be no language-based backward incompatibilities!

**Comment by mathewtrivett** [comment]
👍🏼 thanks. Will upgrade

**Comment by mathewtrivett** [comment]
👍🏼 thanks. Will upgrade
